CREATE TABLE Majors
(
MajorID INT PRIMARY KEY IDENTITY NOT NULL,
[Name] VARCHAR(30)
)

CREATE TABLE Students
(
StudentID INT PRIMARY KEY IDENTITY NOT NULL,
StudentNumber INT NOT NULL,
StudentName VARCHAR(30),
MajorID INT FOREIGN KEY REFERENCES Majors(MajorID)

)

CREATE TABLE Payments
(
PaymentID INT PRIMARY KEY IDENTITY NOT NULL,
PaymentDate DATE NOT NULL,
PaymentAmount MONEY,
StudentID INT FOREIGN KEY REFERENCES Students(StudentID)
)

CREATE TABLE Subjects
(
SubjectID INT PRIMARY KEY IDENTITY NOT NULL,
SubjectName VARCHAR(30)
)

CREATE TABLE Agenda
(
StudentID INT FOREIGN KEY REFERENCES Students(StudentID),
SubjectID INT FOREIGN KEY REFERENCES Subjects(SubjectID)
PRIMARY KEY(StudentID, SubjectID)
)